import { ENGINE_LIMITS } from '#constants/engine.js';

/**
 * Standard values used for validation, snapshots, and high-precision testing.
 */
export const TEST_DEFAULTS = {
    /** Canonical golden snapshots are generated by exhaustive shared searches. */
    SNAPSHOT_EXHAUSTIVE: true,

    /** High-precision threshold for non-exhaustive refinement/performance probes. */
    SNAPSHOT_THRESHOLD: 0.00000001,

    /** Max iterations for non-exhaustive refinement/performance probes. */
    SNAPSHOT_ITERATIONS: ENGINE_LIMITS.MAX_ITERATIONS_UNBOUNDED,

    /** Modern book golden snapshot target: classify 99.95% of probability mass without exhaustive bottom-out. */
    MODERN_BOOK_SNAPSHOT_TARGET_CLASSIFIED_MASS: 0.9995,

    /** Iteration ceiling high enough for the modern book snapshot to reach its 99.95% mass target. */
    MODERN_BOOK_SNAPSHOT_ITERATIONS: 3_000_000,

    /** Results limit for snapshot generation to capture the full distribution tail. */
    SNAPSHOT_RESULTS_LIMIT: ENGINE_LIMITS.MAX_RESULTS_UNBOUNDED,

    /** Floating-point epsilon for statistical assertions. */
    EPSILON_COMPARISON: 1e-12,

    /** Stricter epsilon for mass accounting (bit-perfect parity). */
    EPSILON_ACCOUNTING: 1e-15
};
